import styles from './layout.module.css'

import Sidebar from '@/component/Organisms/Sidebar/Sidebar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function SidebarLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className={styles.container}>
            <div className={styles.childContainer}>{children}</div>
            <div className={styles.sidebarContainer}>
                <Sidebar />
            </div>
        </div>
    )
}
