POST http://localhost:3001/signup
Content-Type: application/json

{
    "name": "long",
    "email": "kieulong1401",
    "password": "123"
    
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "kieulong1401",
    "password": "123"
    
}

###

GET http://localhost:3001/chapterId?comicId=hoang-tu-ban-thuoc-s19444-19444&chapOrder=18


###

GET https://nettruyenfull.com/

###
GET https://nettruyenxx.com/truyen-tranh/hoi-quy-bang-vuong-quyen

###
GET https://cdn.nettruyenss.vn/874/874886/1.jpg?w=2048&q=75&auto=format
