POST http://localhost:3001/signup
Content-Type: application/json

{
    "name": "long",
    "email": "kieulong1401",
    "password": "123"
    
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "kieulong1401",
    "password": "123"
    
}